### ISSUE TITLE
What is the meaning of tvm_generic and tvm_opt?

### ISSUE THREAD

**Issue by onlyoh** [KnowingNothing/FlexTensor#18]
I found there is an argument named type in argument list of `conv2d_baseline.py`, and its value can be `tvm_generic`, `tvm_opt` or `pytorch`. What the meaning of `type`, `tvm_generic` and `tvm_opt`?

**Comment by KnowingNothing** [comment]
`tvm_generic` uses fallback configs of autotvm, which are predefined by experts. `tvm_opt` uses tuning to find configs.
